name: "Testing"

on: [push, pull_request]

env:
  DOTBOT_CMD_BASE: >
    ./dotbot/bin/dotbot -vv -d ./dotbot-ed/tests -p ./dotbot-ed/ed.py

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11-dev"]
    steps:
      - name: Checkout dotbot-ed
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: ./dotbot-ed
      - name: Checkout dotbot
        uses: actions/checkout@v2
        with:
          repository: 'anishathalye/dotbot'
          submodules: recursive
          path: ./dotbot
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Run dotbot (01)"
        run: $DOTBOT_CMD_BASE -c ./dotbot-ed/tests/actions-01-from-empty.yaml
      - name: "Check results (01)"
        run: |
          set -eux
          [ "$(wc -l ~/test-etc-hosts | awk '{print $1}')" = "2" ] || exit 1
          grep -E '^127\.0\.0\.1\s+localhost\s*$' ~/test-etc-hosts
          grep -E '^10\.10\.10\.88\s+wonder-dev-001\s*$' ~/test-etc-hosts
        shell: bash

      - name: "Run dotbot (02)"
        run: $DOTBOT_CMD_BASE -c ./dotbot-ed/tests/actions-02-replay-01.yaml
      - name: "Check results (02)"
        run: |
          set -eux
          [ "$(wc -l ~/test-etc-hosts | awk '{print $1}')" = "2" ] || exit 1
          grep -E '^127\.0\.0\.1\s+localhost\s*$' ~/test-etc-hosts
          grep -E '^10\.10\.10\.88\s+wonder-dev-001\s*$' ~/test-etc-hosts
        shell: bash

      - name: "Run dotbot (03)"
        run: $DOTBOT_CMD_BASE -c ./dotbot-ed/tests/actions-03-new-lines.yaml
      - name: "Check results (03)"
        run: |
          set -eux
          [ "$(wc -l ~/test-etc-hosts | awk '{print $1}')" = "4" ] || exit 1
          grep -E '^127\.0\.0\.1\s+localhost\s*$' ~/test-etc-hosts
          grep -E '^10\.10\.10\.88\s+wonder-dev-001\s*$' ~/test-etc-hosts
          grep -E '^10\.10\.10\.89\s+wonder-dev-002\s*$' ~/test-etc-hosts
          grep -E '^10\.10\.10\.90\s+wonder-dev-003\s*$' ~/test-etc-hosts
        shell: bash
